### ISSUE TITLE
nfOpenJson shortening fields and cannot take more than 10 Fields

### ISSUE THREAD

**Issue by CodyWMitchell** [VFPX/nfJson#11]
I'm running the code below, which is working successfully unless I add an additional field.

**This Works:**
```
nfOpenJson(O.ResponseText,'$.array',';
- attnum v(200) $.attnum;
- salutation v(200) $.salutation;
- first_name v(200) $.first_name;
- last_name v(200) $.last_name;
- phone v(200) $.phone;
- email v(200) $.email;
- address v(200) $.address;
- city v(200) $.city;
- state v(200) $.state;
- age v(200) $.age;
')
```

**This Doesn't Work:**

```
nfOpenJson(O.ResponseText,'$.array',';
- attnum v(200) $.attnum;
- salutation v(200) $.salutation;
- first_name v(200) $.first_name;
- last_name v(200) $.last_name;
- phone v(200) $.phone;
- email v(200) $.email;
- address v(200) $.address;
- city v(200) $.city;
- state v(200) $.state;
- age v(200) $.age;
- dob v(200) $.dob;
')
```
I used dob above, but it doesn't seem to matter what the additional field is, it doesn't work and gives me the error:
"Command contains unrecognized phrase/keyword"

Additionally, when I only use ten or less fields and the query IS successful, it's shortening the values to the length of the first one it encounters.
For example:
![image](https://user-images.githubusercontent.com/39098327/129776581-ab9b8769-d4a6-48f4-a236-427db2fae86c.png)

Here it's shortening **Kayla** and **Randall** to **Kayl** and **Rand**. If I change the length of **Test** to **Testt**, then we get **Kayla** and **Randa**. 

Any help would be appreciated.

**Comment by nfoxdev** [comment]
Hello Cody, 

Thanks for using nfJson.
 nfOpenJson is a  beta function willing to show compatibility with sqlserver syntax;
You can avoid the 255 char limit passing the structure as parameter like this
( you noted there's a bug in nfJson regarding variant columns, use character instead ):


```
TEXT TO cStruct PRETEXT 8
- attnum c(10) $.attnum
- salutation c(10) $.salutation
- first_name c(10) $.first_name
- last_name c(10) $.last_name
- phone c(30) $.phone
- email c(30) $.email
- address c(200) $.address
- city c(20) $.city
- state c(20) $.state
- age i $.age
- dob d $.dob
ENDTEXT

nfOpenJson(O.ResponseText,'$.array',m.cStruct)``

```
Though is convenient,  I no longer support nfOpenJson ; 
instead prefer to use nfJsonRead and a existing destination cursor like this:

```

oResponse = nfJsonRead( o.ResponseText )

Create cursor response (;
 attnum v(200) , salutation v(200) , first_name v(200) ,;
 last_name v(200), phone v(200) , email v(200) , ;
 address v(200) , city v(200) , state v(200) , age v(200) ;
    )

For Each oRow In oResponse.Array
    Insert Into response From Name oRow
Endfor

```

Check the updated nfJsonTest.prg at

[nfOpenJson Test](https://github.com/VFPX/nfJson/blob/master/nfJson/Tests/nfopenjsontest.PRG)

and a discussion with more complex scenarios ( message : 19 Sep 19 16:36 ):

https://www.tek-tips.com/viewthread.cfm?qid=1796615
