### ISSUE TITLE
Lowercase property names

### ISSUE THREAD

**Issue by GeorgiouJohn** [VFPX/nfJson#16]
Hi, I John from Greece.
There is a minor issue with property names in nfjsoncreate. Always export property names with lowercase. Vfp objects have _memberdata property (with XML value) and we can add the displayName of a property .Than we can use the displayName instead of the property name.   What I do now is this:

```
var = lower(am(m.x1))

***new Code
IF PEMSTATUS(obt,'_memberdata',5)
	LOCAL oX,iX
	oX = nfxmlRead(obt._MemberData)
	FOR iX=1 TO ALEN(oX.vfpdata.memberdata)
		IF var == LOWER(oX.vfpdata.memberdata[iX]._attr_.name)
			var = oX.vfpdata.memberdata[iX]._attr_.display
			EXIT 
		ENDIF 
	ENDFOR 
ENDIF 
***end new Code	

este = m.este+iif(m.x1>1,',','')+m.xtabs

```
But this needs nfxmlRead. I believe you can find a better solution.
Thanks for your time.

**Comment by nfoxdev** [comment]
Hello Jhon, thanks for using nfJson.  Yes.. vfp is non case sensitive..  good idea the use for memberdata..!  -I see this xml can be converted directly by xmltocursor  
 so we can save nfXml for more complex objects... so try: 

        var = lower(am(m.x1))

        if type('m.obt._memberdata') = 'C'
            _cur_area = select()
            try
                xmltocursor(obt._memberdata,'_memberdata_')
                dispname = lookup(display,padr(m.var,len(name)),name)
                var = evl(m.dispname,m.var)
                use
            catch
            endtry
            select (_cur_area)
        endif

**Comment by GeorgiouJohn** [comment]
Thanks for the tip. Have a nice day.
