### ISSUE TITLE
private all breaks global variables in error handler

### ISSUE THREAD

**Issue by kobruleht** [VFPX/nfJson#17]
Code to reproduce:

```
PUBLIC public_errormsg
public_errormsg = 'no error'
ON ERROR public_errormsg = MESSAGE()
nfjsonread('causeerror')
ON ERROR
?public_errormsg
```

Observed output:

no error

Expected output:

error description

Code shoud re-factored so that private all is not used.
Simply removing private all commands from nfjsonread source code stops parsing.

**Comment by nfoxdev** [comment]
If you don't use try/catch, use a error routine to manage your errors ( as explained on vfp help ):

ON ERROR DO errHandler WITH   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )

In errHandler() you can access your global variables and perform any other action.

**Comment by cwollenhaupt** [comment]
This isn't only a matter with error handlers. The same problems come up when you use a global variable such as goApp in any of these circumstances:

- In a SKIP FOR clause in the menu
- In a Dynamic... property in a grid
- In the code of an access method of the object that is serialized

This can result is a situation where VFP endlessly displays error messages until you terminate the process from Task Manager.

**Comment by nfoxdev** [comment]
Until the new release, a solution for current users facing the scenarios mentioned is to use screen properties instead of global variables, as previously suggested.
