### ISSUE TITLE
Unicode Issue

### ISSUE THREAD

**Issue by rafahoff** [VFPX/nfJson#5]
Hi there,

Firstly, thanks for sharing this tool.

I'm dealing with some problems converting unicode strings. 
The JSON which my software consumes comes from Telegram API (getUpdates).

Could you take a look and give some ideas how to solve that?

As I discovered the emojis and other PT-BR chars are the error's reason.

Attached there are two JSONs: one before unicode conversion and the second after unicode conversion (I used Notepad++ plugin for this job).

[JSONs.zip](https://github.com/VFPX/nfJson/files/3050846/JSONs.zip)

My call: 

`oJson = nfJsonRead(lcJSON,.T. )`

![image](https://user-images.githubusercontent.com/49349559/55674180-48fed400-5887-11e9-8616-9942f1b7447a.png)

Regards,
Rafael Hoffmann
Brazil

**Comment by mplazac** [comment]
Hi, Rafael,

- The initial version managed characters up to 32767 ( parameter '2' in bintoc() function ). Limitation is now removed, so nfJson won't throw error.

- Emojis and any other unicode character wich can't be represented in ASCII are returned in html codification so you can handle it in vfp with no hassle. 
 
- The "\n" is the json encoded new line character; nfJson returns it as expected ( a new line in your string ).
