### ISSUE TITLE
Incorrect property name ???

### ISSUE THREAD

**Issue by StoyanMalchev** [VFPX/nfJson#8]
TEXT TO lcJSON NOSHOW 
{
  "deviceDateTime": "2019-05-31T18:11:55",
  "ok": true,
  "messages": [
    {  "type": "info",
      "code": "",
      "text": "Serial number"  },
    { "type": "info",
      "code": "",
      "text": "FM is formatted"  }
  ]
} 
endtext

oECR = json_decode(lcJSON)

**Comment by nftools** [comment]
Hi Stoyan,  I'm  assuming you renamed nfJsonRead.prg to json_decode.prg. 
"messages" is a function name. We cannot define arrays with that name and any other VFP function name. To circunveil the problem nfJson will add the suffix "_vfpsafe_ "  The same way, nfJsonCreate() will remove the suffix automatically.
