### ISSUE TITLE
Json with multiple structures

### ISSUE THREAD

**Issue by decentrajan** [VFPX/nfJson#9]
Hi i have a problem that json have multiple structure mean to say one json have 5 tables and wsnt to retrieve all tables in each dbf
How to work

**Comment by mplazac** [comment]
Hi, the easiest ( and recommended way ) is to:

1) create destination cursor(s) 
2) Parse json string using nfJsonRead()
3) iterate each array and fill each destination cursor using scatter name / insert into ... from name

You can find a sample working code and discussion of this and some other complex scenarios on this post: **19 Sep 19 16:36** at  Tek-Tips  [https://www.tek-tips.com/viewthread.cfm?qid=1796615](url)
